const defaults={panelUrl:'http://localhost:3000',copilotKey:'change-me',autoSubmit:false,defaultDuration:'',freelancerProfile:'',preferredDomains:[],minMatchScore:70,minJobScore:65};
const checks=()=>[...document.querySelectorAll('.domainCheck')];
function setDomainChecks(values=[]){const set=new Set(values||[]);checks().forEach(el=>el.checked=set.has(el.value));}
function selectedDomains(){return checks().filter(el=>el.checked).map(el=>el.value);}
function updateHint(profile, explicit=[]){const inferred=globalThis.CopilotDomain?.inferAllowedDomains(profile||'')||[];const labels=(explicit.length?explicit:inferred).map(k=>globalThis.CopilotDomain?.DOMAIN_DEFS?.[k]?.label||k);document.getElementById('domainHint').textContent=explicit.length?`حوزه‌های صریح: ${labels.join('، ')}`:inferred.length?`فعلاً از پروفایل استنباط می‌شود: ${labels.join('، ')}`:'هیچ حوزه‌ای با اطمینان تشخیص داده نشده؛ برای جلوگیری از بید اشتباه، پروژه‌های دارای حوزه مشخص SKIP می‌شوند تا حوزه کاری را تعیین کنی.';}
chrome.storage.sync.get(defaults,s=>{Object.entries(s).forEach(([k,v])=>{if(k==='preferredDomains')return;const el=document.getElementById(k);if(!el)return;if(el.type==='checkbox')el.checked=!!v;else el.value=v??'';});setDomainChecks(s.preferredDomains||[]);updateHint(s.freelancerProfile||'',s.preferredDomains||[]);});
document.getElementById('inferDomains').onclick=()=>{const profile=document.getElementById('freelancerProfile').value.trim();const inferred=globalThis.CopilotDomain?.inferAllowedDomains(profile)||[];setDomainChecks(inferred);updateHint(profile,inferred);};
document.getElementById('freelancerProfile').addEventListener('input',e=>updateHint(e.target.value,selectedDomains()));
checks().forEach(el=>el.addEventListener('change',()=>updateHint(document.getElementById('freelancerProfile').value.trim(),selectedDomains())));
document.getElementById('save').onclick=async()=>{const data={panelUrl:document.getElementById('panelUrl').value.trim().replace(/\/$/,''),copilotKey:document.getElementById('copilotKey').value,freelancerProfile:document.getElementById('freelancerProfile').value.trim(),preferredDomains:selectedDomains(),defaultDuration:document.getElementById('defaultDuration').value.trim(),minMatchScore:Number(document.getElementById('minMatchScore').value||70),minJobScore:Number(document.getElementById('minJobScore').value||65),autoSubmit:document.getElementById('autoSubmit').checked};await chrome.storage.sync.set(data);await chrome.storage.local.remove(['scanQueue','latestGenerated']);updateHint(data.freelancerProfile,data.preferredDomains);document.getElementById('saved').textContent='ذخیره شد.';setTimeout(()=>document.getElementById('saved').textContent='',1600);};
document.getElementById('clearHistory').onclick=async()=>{await chrome.storage.local.set({bidHistory:{}});document.getElementById('saved').textContent='تاریخچه گاردها پاک شد.';};
