const defaults={panelUrl:'https://www.freelancerpanel.ir',copilotKey:'change-me',autoSubmit:true,defaultDuration:'',freelancerProfile:'',preferredDomains:[],minMatchScore:70,minJobScore:65};
const checks=()=>[...document.querySelectorAll('.domainCheck')];
function setDomainChecks(values=[]){const set=new Set(values||[]);checks().forEach(el=>el.checked=set.has(el.value));}
function selectedDomains(){return checks().filter(el=>el.checked).map(el=>el.value);}
function updateHint(profile, explicit=[]){const inferred=globalThis.CopilotDomain?.inferAllowedDomains(profile||'')||[];const labels=(explicit.length?explicit:inferred).map(k=>globalThis.CopilotDomain?.DOMAIN_DEFS?.[k]?.label||k);document.getElementById('domainHint').textContent=explicit.length?`حوزه‌های صریح: ${labels.join('، ')}`:inferred.length?`فعلاً از پروفایل استنباط می‌شود: ${labels.join('، ')}`:'هیچ حوزه‌ای با اطمینان تشخیص داده نشده؛ برای جلوگیری از بید اشتباه، پروژه‌های دارای حوزه مشخص SKIP می‌شوند تا حوزه کاری را تعیین کنی.';}
chrome.storage.sync.get(defaults,s=>{Object.entries(s).forEach(([k,v])=>{if(k==='preferredDomains')return;const el=document.getElementById(k);if(!el)return;if(el.type==='checkbox')el.checked=!!v;else el.value=v??'';});setDomainChecks(s.preferredDomains||[]);updateHint(s.freelancerProfile||'',s.preferredDomains||[]);});
document.getElementById('inferDomains').onclick=()=>{const profile=document.getElementById('freelancerProfile').value.trim();const inferred=globalThis.CopilotDomain?.inferAllowedDomains(profile)||[];setDomainChecks(inferred);updateHint(profile,inferred);};
document.getElementById('freelancerProfile').addEventListener('input',e=>updateHint(e.target.value,selectedDomains()));
checks().forEach(el=>el.addEventListener('change',()=>updateHint(document.getElementById('freelancerProfile').value.trim(),selectedDomains())));
document.getElementById('save').onclick=async()=>{const saved=document.getElementById('saved');const data={panelUrl:document.getElementById('panelUrl').value.trim().replace(/\/$/,''),copilotKey:document.getElementById('copilotKey').value,freelancerProfile:document.getElementById('freelancerProfile').value.trim(),preferredDomains:selectedDomains(),defaultDuration:document.getElementById('defaultDuration').value.trim(),minMatchScore:Number(document.getElementById('minMatchScore').value||70),minJobScore:Number(document.getElementById('minJobScore').value||65),autoSubmit:document.getElementById('autoSubmit').checked};try{if(!/^https:\/\//i.test(data.panelUrl)&&!/^http:\/\/localhost(?::\d+)?$/i.test(data.panelUrl))throw new Error('آدرس پنل معتبر نیست.');if(!data.copilotKey||data.copilotKey==='change-me')throw new Error('COPILOT_KEY را وارد کن.');saved.textContent='در حال آزمایش اتصال و موتور بید…';const response=await fetch(`${data.panelUrl}/api/health`,{headers:{'X-Copilot-Key':data.copilotKey},cache:'no-store'});const health=await response.json().catch(()=>({}));if(!response.ok)throw new Error(response.status===401?'COPILOT_KEY صحیح نیست.':`پنل پاسخ ${response.status} داد.`);if(!health.aiConfigured)throw new Error('اتصال پنل برقرار است اما OPENAI_API_KEY یا OPENAI_MODEL تنظیم نشده؛ تولید بید متوقف می‌ماند.');await chrome.storage.sync.set(data);await chrome.storage.local.remove(['scanQueue','latestGenerated']);updateHint(data.freelancerProfile,data.preferredDomains);saved.textContent=`اتصال موفق؛ موتور AI و نسخه ${health.version||''} آماده است.`;}catch(error){saved.textContent=error?.message||'اتصال ناموفق بود.';}setTimeout(()=>saved.textContent='',5500);};
document.getElementById('clearHistory').onclick=async()=>{await chrome.storage.local.set({bidHistory:{}});document.getElementById('saved').textContent='تاریخچه گاردها پاک شد.';};
